# Generated by Django 5.0.6 on 2026-03-21 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants.coupon",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("customizations", models.JSONField(default=list)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "cart_items",
                "unique_together": {("cart", "menu_item")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=26, primary_key=True, serialize=False
                    ),
                ),
                ("items", models.JSONField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=5, max_digits=6),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("taxes", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("coupon_code", models.CharField(blank=True, max_length=30)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("cod", "Cash on Delivery"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("placed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("preparing_at", models.DateTimeField(blank=True, null=True)),
                ("out_for_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.address",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-placed_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"], name="orders_custome_58f6c3_idx"
                    ),
                    models.Index(
                        fields=["restaurant", "status"],
                        name="orders_restaur_0aeb84_idx",
                    ),
                ],
            },
        ),
    ]
