# Generated by Django 5.0.6 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_cancellation_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("card", "Card"),
                    ("netbanking", "Net Banking"),
                    ("cod", "Cash on Delivery"),
                ],
                max_length=10,
            ),
        ),
    ]
