# Generated by Django 5.0.6 on 2026-03-21 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("warm", "Warm & Grateful"),
                            ("apologetic", "Empathetic & Recovery"),
                            ("professional", "Professional & Brief"),
                            ("custom", "Custom"),
                        ],
                        default="warm",
                        max_length=20,
                    ),
                ),
                ("prompt_instructions", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_templates",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_templates",
                "ordering": ["-is_active", "-usage_count"],
            },
        ),
    ]
