[phases.setup]
nixPkgs = ["python312", "gcc", "libpq"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn config.wsgi:application --config gunicorn.conf.py"
