# Generated by Django 5.0.6 on 2026-03-21 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat")],
                        max_length=15,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "min_order",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "coupons",
            },
        ),
        migrations.CreateModel(
            name="CuisineCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("icon", models.CharField(max_length=10)),
                ("color", models.CharField(default="#E8A830", max_length=10)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "cuisine_categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=10)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "menu_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("image", models.URLField(blank=True)),
                ("is_veg", models.BooleanField(default=True)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "spice_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("hot", "Hot"),
                            ("extra-hot", "Extra Hot"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "customizations",
                    models.JSONField(
                        default=list,
                        help_text='[{"name": "Extra Sambar", "price": 10}]',
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurants.menucategory",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("cuisine_tags", models.JSONField(default=list)),
                ("thumbnail", models.URLField(blank=True)),
                ("cover_image", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "timings",
                    models.CharField(
                        blank=True, default="09:00 AM - 10:00 PM", max_length=100
                    ),
                ),
                ("fssai", models.CharField(blank=True, max_length=20)),
                ("is_open", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_order",
                    models.DecimalField(decimal_places=2, default=100, max_digits=8),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=30, max_digits=6),
                ),
                (
                    "avg_delivery_time",
                    models.PositiveSmallIntegerField(default=30, help_text="Minutes"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("percentage", "Percentage"), ("flat", "Flat")],
                        max_length=15,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("discount_label", models.CharField(blank=True, max_length=100)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        limit_choices_to={"role": "hotel_admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "restaurants",
                "ordering": ["-is_featured", "-rating_avg"],
            },
        ),
        migrations.AddField(
            model_name="menucategory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["city", "is_active"], name="restaurants_city_19f308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["rating_avg"], name="restaurants_rating__fb5785_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("restaurant", "name")},
        ),
    ]
